name: circexplorer3
channels:
  - bioconda
  - bioinfo
  - conda-forge
  - defaults

dependencies:
  - python=2.7
  - numpy
  - pysam=0.9.0
  - hisat2=2.0.5
  - StringTie=1.3.6
  - ucsc-gtftogenepred
  - ucsc-genepredtogtf
  - tophat=2.0.13
  - bowtie2
  - bowtie=1.0.0.0
  - bedtools
  - pip
  - git
  - pybedtools=0.7.5
  - pip:
    - circexplorer2==2.3.6
    - docopt
    - idna
    - requests
    - urllib3
