#!/bin/bash -l
#$ -P   casa
#$ -cwd 

#run for test: qsub runCIR3.qsub 1004-minus_174_019_S63_L002
name=${1}

echo "Calling container"
singularity run --no-home --bind ./inputdata:/inputdata,./result:/result,/restricted/projectnb/casa/mtLin/reference:/reference cir3.sif ${name}
echo "exit Container"

# remove files 
# rm -rf ./result/${name}/hisat/align.sam 
# rm -rf ./inputdata/${name}_R1.fastq ./inputdata/${name}_R2.fastq